#!/bin/sh

# xinitrc for i3 Window Manager

# Start a terminal
termite &

# Start screensaver
# Kill gnome-screensaver if started by default
killall gnome-screensaver &
xscreensaver -no-splash &

# Start sound server
pulseaudio --start &

redshift &

xautolock -time 10 -locker ~/.scripts/i3/i3_lock.sh &

exec i3
