#!/bin/sh

###########################################
# File: dotfiles/.scripts/arch/i3/xinitrc
# Script Group: Desktop
# Platform: Arch
# Purpose: To provide startup info for i3
###########################################


# Start a terminal
termite &

# Start screensaver
# Kill gnome-screensaver if started by default
killall gnome-screensaver &
xscreensaver -no-splash &

# Start sound server
pulseaudio --start &

redshift &

xautolock -time 10 -locker ~/.scripts/i3/i3_lock.sh &

exec i3
